@baseUrl = http://localhost:4001

# AUTH ENDPOINTS
# Register a new user
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

    {
        "email": "kene2@gmail.com",
        "password":"passcode",
        "firstName":"Kene",
        "lastName":"Kamau"
    }

###

# Login a user
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

    {
        "email": "kene2@gmail.com",
        "password":"passcode",
    }

###

# Logout a user
POST {{baseUrl}}/api/auth/logout

###

# GET ALL DOCS
GET {{baseUrl}}/api/doc/users?limit=5

###

# GET DOC BY ID
GET {{baseUrl}}/api/doc/users/62a4302f8113cd0627bd9e16

